Import('env', 'envCython', 'common', 'messaging')

libs = ['usb-1.0', common, messaging, 'pthread']
panda = env.Library('panda', ['panda.cc', 'panda_comms.cc', 'spi.cc'])

env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)
env.Library('libcan_list_to_can_capnp', ['can_list_to_can_capnp.cc'])

pandad_python = envCython.Program('pandad_api_impl.so', 'pandad_api_impl.pyx', LIBS=["can_list_to_can_capnp", 'capnp', 'kj'] + envCython["LIBS"],
    LIBPATH=[
        '.',  # current directory
        'selfdrive/pandad',  # path to libcan_list_to_can_capnp.a
        'third_party',
        'msgq_repo',
        'common',
        'rednose/helpers',
        '/usr/lib',
        '/usr/local/lib',
    ]


)


Export('pandad_python')

if GetOption('extras'):
  env.Program('tests/test_pandad_usbprotocol', ['tests/test_pandad_usbprotocol.cc'], LIBS=[panda] + libs)
